import sys
import os
from .core import VacationExtender

# --- Default Configuration Template ---
# This string ensures that users installing via pip can generate 
# a valid config file anywhere without needing external file assets.
DEFAULT_CONFIG = """# =================================================================
# VACATION EXTENDER CONFIGURATION
# Generated by VacationExtender
# Source: https://github.com/afsmaira/vacationExtender
# =================================================================

[CALENDAR]
# The target year (Integer). Default: next year
year = 2026

# Weekend definition (0 = Mon, 6 = Sun). Default: [5, 6] (Sat, Sun)
weekend = [5, 6]

[LOCATION]
# ISO 3166-1 alpha-2 country code (e.g., "BR", "US", "CA")
country_code = "BR"

# Subdivision code (State/Province). Use "" for none.
subdivision_code = "SP"

# Observe holidays falling on weekends on the next workday? (True/False)
include_observed = false

[CONSTRAINTS]
# Total vacation days available in the budget
vacation_days = 30

# Maximum number of distinct vacation periods allowed
max_vac_periods = 3

# Minimum/Maximum days per single break (PTO + Holidays + Weekend)
min_vac_days_per_break = 5
max_vac_days_per_break = 20

# Minimum days gap between two vacation periods
min_gap_days = 60

# Number of suggestions to display
top_n_suggestions = 1

# Additional holidays (e.g., local holidays or company bridges).
# Accepted formats in the list:
#   - Single day: "YYYY-MM-DD"
#   - Interval:   "YYYY-MM-DD:YYYY-MM-DD" (Start:End)
custom_holidays = []

# Mandatory work days or intervals (dates where you CANNOT take vacation).
# Same format as custom_holidays.
forced_work = []

[ALGORITHM]
# 'optimal' (Slow, Perfect) or 'greedy' (Fast, Heuristic)
algorithm_type = "optimal"

# Alpha Factor (0.0 to 1.0). 
# Higher values prefer longer consecutive breaks over total days off.
duration_weight_factor_alpha = 0.5
"""


def main():
    """Entry point for the console script."""
    if len(sys.argv) > 1 and sys.argv[1] == "init":
        target_file = "config.toml"

        if os.path.exists(target_file):
            print(f"⚠️ WARNING: '{target_file}' already exists in this directory.")
            print("  Delete it first if you want to regenerate the default config.")
        else:
            try:
                with open(target_file, "w", encoding="utf-8") as f:
                    f.write(DEFAULT_CONFIG)
                print(f"✅  SUCCESS: Default configuration created at '{os.path.abspath(target_file)}'.")
                print("   👉 Open it, edit your preferences, and run 'vacation-extender' again.")
            except Exception as e:
                print(f"❌  ERROR: Could not write file. Reason: {e}")
        return

    config_path = "config.toml"
    if not os.path.exists(config_path):
        print("❌  ERROR: Configuration file 'config.toml' not found.")
        print("💡  TIP: Run 'vacation-extender init' to generate a default file.")
        return

    # Run the application
    try:
        ve = VacationExtender(config_path)
        ve.run()
        print(ve)
    except Exception as e:
        # Catch unexpected crashes to give a cleaner error message
        print(f"❌  CRITICAL ERROR: {e}")
        # Uncomment the line below for debugging:
        # raise e


if __name__ == "__main__":
    main()
